project:
  type: website
  output-dir: ../docs  # Render output to the 'docs' folder for GitHub Pages

website:
  title: "Archaeologists - humanitées numeriques"  # Title of your wiki
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Setup.qmd
        text: Setup
      - href: Introduction-SPARQLchunks.qmd
        text: Introduction to SPARQLchunks
  page-footer: "© 2025 Jonathan Schmidt."

format:
  html:
    toc: true      # Enable table of contents
    toc-depth: 3   # Limit TOC to 3 levels
    theme: cosmo   # Choose a Bootstrap theme
    #css: styles.css  # Optional: Custom CSS file

execute:
  freeze: auto  # Re-render only if source file changes